export const Urls = {
    base_url : 'http://dihsan.datawalls.ca/api/',
    login : 'users/login',
    userList : 'users',
    roleList : 'users/roles',
    updateUser: 'users/',
    createUser: 'users/',
    getRoleAccess: 'users/roles_menus_access/get_role_with_access',
    updateRoleAccess: 'users/roles_menus_access/bulk_update',
    suppliers: 'stakeholders/supplier',
    designers: 'stakeholders/designer',
    endpoints: 'services/endpoint',
    resources: 'services/resource',
    syncEndpoint: 'product/sync_endpoint',
    syncresouce: 'product/sync_api',
    syncSupplier: 'product/sync_supplier',
    product: 'product/',
    syncAll: 'product/sync_all',
    fields_mapping: 'services/fields_mapping',
    bulk_update_field: 'services/fields_mapping/bulk_update',
    bulk_update_category_field: 'product/categoryfieldsmapping/bulk_update',
    categoryList: 'product/category',
    subcategoryList: 'product/subcategory',
    sizeList: 'product/size',
    genderList: 'product/gender',
    colorList: 'product/color',
    schedules: 'services/schedule',
    productImage: 'product/productimage',
    fieldMap: 'services/fields_mapping',
    bulkUpdate: 'product/productimage/bulk_update',
    configuration: 'services/settings',
    categoryFieldMapping: 'product/categoryfieldsmapping',
    allCategories: 'product/categories',
    assignTo: 'product/assign_to',
    order: 'product/order',

    change_password: 'users/change_password',
}