export const dataTable = [
    {
      "id": 83,
      "supplier_id": 0,
      "designer_id": 33,
      "category_id": 26,
      "sub_category_id": "$2,787.68",
      "subtitle": 29,
      "highlights": "green",
      "name": "Myra James",
      "details": "female",
      "company": "VANTAGE",
      "retail_price": "$2,433.15",
      "final_price": "$2,870.51",
      "is_active": false,
      "shipping": "841 Grimes Road, Macdona, Louisiana, 8131"
    },
    {
      "id": 78,
      "supplier_id": 1,
      "designer_id": 38,
      "category_id": 23,
      "sub_category_id": "$3,369.63",
      "subtitle": 21,
      "highlights": "green",
      "name": "Lynnette Hebert",
      "details": "female",
      "company": "PLASMOSIS",
      "retail_price": "$3,187.87",
      "final_price": "$3,234.49",
      "is_active": true,
      "shipping": "729 Oxford Street, Falmouth, Nevada, 8377"
    },
    {
      "id": 87,
      "supplier_id": 2,
      "designer_id": 33,
      "category_id": 30,
      "sub_category_id": "$3,130.81",
      "subtitle": 30,
      "highlights": "brown",
      "name": "Ingrid Brown",
      "details": "female",
      "company": "ACCUPRINT",
      "retail_price": "$3,883.74",
      "final_price": "$1,759.90",
      "is_active": true,
      "shipping": "424 Bushwick Court, Savage, Arkansas, 3035"
    },
    {
      "id": 74,
      "supplier_id": 3,
      "designer_id": 31,
      "category_id": 32,
      "sub_category_id": "$3,120.84",
      "subtitle": 30,
      "highlights": "brown",
      "name": "Pansy Moreno",
      "details": "female",
      "company": "TURNLING",
      "retail_price": "$3,904.80",
      "final_price": "$3,232.87",
      "is_active": false,
      "shipping": "209 Polar Street, Suitland, Virgin Islands, 8234"
    },
    {
      "id": 89,
      "supplier_id": 4,
      "designer_id": 28,
      "category_id": 39,
      "sub_category_id": "$3,663.11",
      "subtitle": 25,
      "highlights": "green",
      "name": "Shannon Jarvis",
      "details": "male",
      "company": "ROOFORIA",
      "retail_price": "$1,717.43",
      "final_price": "$1,406.85",
      "is_active": true,
      "shipping": "467 Cheever Place, Dunbar, Marshall Islands, 8789"
    },
    {
      "id": 89,
      "supplier_id": 5,
      "designer_id": 28,
      "category_id": 28,
      "sub_category_id": "$3,999.72",
      "subtitle": 34,
      "highlights": "brown",
      "name": "Zelma Leonard",
      "details": "female",
      "company": "GORGANIC",
      "retail_price": "$3,962.79",
      "final_price": "$1,585.01",
      "is_active": false,
      "shipping": "724 Catherine Street, Chilton, Washington, 2044"
    },
    {
      "id": 84,
      "supplier_id": 6,
      "designer_id": 26,
      "category_id": 23,
      "sub_category_id": "$2,948.79",
      "subtitle": 28,
      "highlights": "blue",
      "name": "Hull Marks",
      "details": "male",
      "company": "INCUBUS",
      "retail_price": "$2,225.67",
      "final_price": "$3,181.97",
      "is_active": false,
      "shipping": "738 Fulton Street, Whitmer, Michigan, 4751"
    },
    {
      "id": 73,
      "supplier_id": 7,
      "designer_id": 21,
      "category_id": 34,
      "sub_category_id": "$2,463.14",
      "subtitle": 29,
      "highlights": "green",
      "name": "Trina Flowers",
      "details": "female",
      "company": "TECHADE",
      "retail_price": "$1,427.78",
      "final_price": "$2,339.81",
      "is_active": false,
      "shipping": "552 Homecrest Avenue, Woodburn, Utah, 9460"
    },
    {
      "id": 85,
      "supplier_id": 8,
      "designer_id": 39,
      "category_id": 40,
      "sub_category_id": "$1,003.63",
      "subtitle": 33,
      "highlights": "green",
      "name": "Adkins Branch",
      "details": "male",
      "company": "DAISU",
      "retail_price": "$2,841.89",
      "final_price": "$3,105.91",
      "is_active": true,
      "shipping": "927 Noel Avenue, Salunga, Montana, 3629"
    },
    {
      "id": 71,
      "supplier_id": 9,
      "designer_id": 28,
      "category_id": 23,
      "sub_category_id": "$2,868.62",
      "subtitle": 25,
      "highlights": "blue",
      "name": "Holly Hinton",
      "details": "female",
      "company": "COMTOURS",
      "retail_price": "$3,256.57",
      "final_price": "$2,973.23",
      "is_active": true,
      "shipping": "348 Decatur Street, Adelino, Georgia, 6620"
    },
    {
      "id": 88,
      "supplier_id": 10,
      "designer_id": 36,
      "category_id": 34,
      "sub_category_id": "$2,387.24",
      "subtitle": 37,
      "highlights": "blue",
      "name": "Latisha Dalton",
      "details": "female",
      "company": "AQUACINE",
      "retail_price": "$2,567.12",
      "final_price": "$3,021.67",
      "is_active": true,
      "shipping": "231 Granite Street, Swartzville, Puerto Rico, 3131"
    }
  ]